######################################################
###############   R Code for the Book  ###############
# Modern Calculus with R: Ideas, Methods and Computing
# By Samuel S.P. Shen
# Distinguished Professor of Mathematics and Statistics
# San Diego State University
# https://shen.sdsu.edu
# Email:sshen@sdsu.edu
# Version 2.0 developed from January 2022 for Cal III
# Version 1.0 developed from May 2021 for Cal III
#
######################################################

##############################################################
################## Basics of R Programming ###################
##############################################################

# R as a Smart Calculator
#########################
1+4
#[1] 5 
#The text behind the symbol # is a comment for R 
plot(2, col = 'red')

2 + pi/4-0.8 
#pi is circumference ratio approximately 3.1415926 
#[1] 1.985398

x<-1 
# <- is the assign symbol: assign 1 to x.
y<-2
z<-4
t<-2*x^y-z 
#equivalent to 2*1ˆ2-4 =-2
t
#[1] -2

u=2 
v <- 3
# Symbols "=" and "<-" are equivalent in most cases v=3
u+v
#[1] 5
sin(u*v) # u*v = 6 is considered radian
#[1] -0.2794155


#Write a function in R
######################
square <- function(x) x*x 
square(4)
#[1] 16

sam <- function(x) {x*x + sin(x)}
sam(2)
plot(sam, col = 'red', lwd = 5)

fctn <- function(x,y,z) {x+y-z/2} 
fctn(1,2,3)
#[1] 1.5


#Plot with R
############
plot(sin, -2*pi, 2*pi, col = 'blue', lwd =2) 
#plot the curve of y=sin(x) from -pi to 2 pi 
x = seq(-9, 9, length = 200)
y = sin(2*x)
plot(x, y,  col = 'red', lwd = 2, 
     pch = 16, cex = 0.5, type = 'l') 

plot(1,2)
plot(c(1,2))
plot(c(1), c(2)) #the best

x = c(1)
y = c(2)
plot(x,y)

plot(c(1,2), c(3, 4))

x = c(1, 2)
y = c(3, 4)
plot(x,y, 
     xlim = c(-4, 4),
     ylim = c(-4, 4))

x = c(1, 2, 3, 4)
y = c(3, 4, -2, -4)
plot(x, y, 
     xlim = c(-4, 4),
     ylim = c(-4, 4))

x = seq(1, 10)
x
y = x^2
y
plot(x, y)

n = 10
x = seq(1, n)
x
y = x^2
y
plot(x, y, type = "o")

square <- function(x) x*x 
#Define a function

plot(square, -3, 2)
# Plot the defined function

fctn(1,2,3)
#[1] 1.5

# Plot a 3D surface using the following code
x = y = seq(-1, 1, length=100)
Z = outer(x, y, function(x, y){1+x^2+y^2})
#outer (x,y, function) is outer product
persp(x=x, y=y, z=Z, theta=310)
# yields a 3D surface with perspective angle 310 deg


#Symbolic Calculation for Calculus by R
#######################################

D(expression(x^2,'x'), 'x')
# Take derivative of x^2 and the answer is 2x
#2 * x

fx = expression(x^2,'x') 
#define a symbolic function with variable x D(fx,’x’)
#differentiate the function and yield a result below
D(fx, 'x')
#2 * x

xt = expression(2*t*cos(t),'t') 
#define a symbolic function with variable x D(fx,’x’)
#differentiate the function and yield a result below
D(xt, 't')
#2 * cos(t) - 2 * t * sin(t)
D(D(xt, 't'), 't') #second derivative
#-(2 * sin(t) + (2 * sin(t) + 2 * t * cos(t)))

sam = expression((1 + x^2)*sin(x^3),'x') 
sam
samD1 = D(sam, 'x')
samD1
#2 * x * sin(x^3) + (1 + x^2) * (cos(x^3) * (3 * x^2))
samD2 = D(samD1, 'x')
samD2
samD3 = D(samD2, 'x')
samD3
D(samD3, 'x')

patient = expression(exp(x), 'x')
patient
D(patient, 'x')

fx = expression(x^2*sin(x),'x')
#Change the expression and use the same derivative command
D(fx,'x')
#2 * x * sin(x) + x^2 * cos(x)

#Symbolic calculation Method 2 
#by the library mosaicCalc
#install.packages('mosaicCalc')
library(mosaicCalc)
D(x^2 ~ x)
#2 * x
antiD(2*x ~ x)
#1 * x^2 + C

D(2*t*cos(2*t) ~ t)

F = antiD(x ~x)
F(1)-F(0)
#[1] 0.5

fxy = expression(3 - x^2 - 2*y^2, 'x','y')
fxy
D(fxy, 'x')
#-(2 * x)
D(fxy, 'y')
# -(2 * (2 * y))

#D(3 - x^2 - 2*y^2 ~ x)

#more variables
fxyz = expression(x^2+y^2+z^2, 'x','y','z')
#define a function of two or more variables
fxyz 
#This gives the expression of the function in terms of x, y and z 
#expression(xˆ2 + yˆ2 + zˆ2, "x", "y", "z")

D(fxyz,'x') 
#This gives the partial derivative with respect to x: 2 * x 
D(fxyz,'y')
#This gives the partial derivative with respect to y: 2 * y 

#Exercise 7.12
#more variables
u = expression(sin(x - c*t), 'x','t')
#define a function of two or more variables
u
#This gives the expression of the function in terms of x, y and z 
#expression(xˆ2 + yˆ2 + zˆ2, "x", "y", "z")

ux = D(u,'x') 
ux
#This gives the partial derivative with respect to x: 2 * x 
ut = D(u,'t')
ut

# functions with constants 
fxa = expression(a*x^2, 'x')
D(fxa, 'x')
#a * (2 * x)
fxn = expression(x^n, 'x')
D(fxn, 'x')
#x^(n - 1) * n
sxan = expression(a*sin(n*x), 'x')
sxan
D(sxan, 'x')
#a * (cos(n * x) * n)

#Partial derivatives in Midterm 2 Problem 1
fxyt = expression(3*cos(3*x + y)*exp(-0.2*t), 'x','y','t')
#define a function of two or more variables
fxyt 
#This gives the expression of the function in terms of x, y and t 
# expression(3 * cos(3 * x + y) * exp(-0.2 * t), "x", "y", "t")

D(fxyt,'x') 
#This gives the partial derivative with respect to x: 
#-(3 * (sin(3 * x + y) * 3) * exp(-0.2 * t))
D(fxyt,'y')
#This gives the partial derivative with respect to y: 
#-(3 * sin(3 * x + y) * exp(-0.2 * t))
D(fxyt,'t')
#This gives the partial derivative with respect to t: 
#-(3 * cos(3 * x + y) * (exp(-0.2 * t) * 0.2))

square = function(x) x^2
integrate (square, 0,1) 
sam2 = function(x){(1 + x^2) * sin(x^3)}
sam2
integrate(sam2, 0,1)
#Integrate xˆ2 from 0 to 1 equals to 1/3 with details below
#0.3333333 with absolute error < 3.7e-15

fc = function(x){cos(x)}
integrate(fc, 0, pi/2)

integrate(cos,0,pi/2) 
#Integrate cos(x) from 0 to pi/2 equals to 1 with details below
#1 with absolute error < 1.1e-14

# symbolic expression() cannot be used for numerics
a =2; n = 3
integrate(sxan,0, pi/2) 
#Error in get(as.character(FUN), mode = "function"

# use function for numerics
sxan2 = function(x){a*sin(n*x)}
integrate(sxan2, 0, pi/2) 
#0.6666667 with absolute error < 2.2e-14

# Antiderivative
#install.packages('mosaicCalc')
library(mosaicCalc)
antiD(x^2 ~ x)
#function (x, C = 0) 
#  1/3 * x^3 + C
antiD(sin(2*x) ~ x)
#1/2 * -cos(2 * x) + C

sam = expression(x^2, 'x')
antiD(sam ~ x) #not working
sam = function(x) x^2
antiD(sam ~ x) # not working

antiD((sin(2*x))^2 ~ x) #not working

#Vectors and Matrices
#####################

c(1,6,3,pi,-3) 
#Enter data inside c() for a 4X1 column vector 
#[1] 1.000000 6.000000 3.000000 3.141593 -3.000000

seq(2,6) 
#Generate a sequence from 2 to 6
#[1] 2 3 4 5 6 
#This is the resulting sequence

seq(1,10,2) 
# Generate a sequence from 1 to 10 with 2 increment
#[1] 1 3 5 7 9

x=c(1,-1,1,-1)
x+1 
#1 is added to each element of x
#[1] 2 0 2 0

2*x 
#2 multiplies each element of x
#[1] 2 -2 2 -2

x/2 
# Each element of x is divided by 2
#[1] 0.5 -0.5 0.5 -0.5

y=seq(1,4)
x*y 
# This * multiples each pair of elements

t(x) 
# Transpose of a matrix
#   [,1] [,2] [,3] [,4]
#[1,] 1   -1    1   -1

t(x)%*%y 
#Matrix multiplication: 1X4 matrix times a 4X1 matrix 
#This is equivalent to a dot product
#    [,1]
#[1,] -2

u = c(3, 4)
v = c(-2.5, 1.5)
nu = norm(u, type = '2')
nv = norm(v, type = '2') 
dotuv = sum(u*v)
c = dotuv/(nu*nv)
c
acos(c)*180/pi
#[1] 95.90614

u = c(1,1,0)
v = c(1,-1,0)
nu = norm(u, type = '2')
nv = norm(v, type = '2') 
dotuv = sum(u*v)
c = dotuv/(nu*nv)
c
acos(c)*180/pi
#[1] 90

acos(sum(u*v)/(norm(u, type = '2')*norm(v, type = '2')))*180/pi
#[1] 95.90614

#Cross product, dot product
# R Program illustrating 
# cross product of two vectors 
# Import the required library 
library(pracma) 
# Taking two vectors 
a = c(3, 5, 4) 
b = c(2, 7, 5) 
# Calculating cross product using cross() 
cross(a, b)
dot(a,b)

x%*%t(y) 
#4X1 matrix times a 1X4 matrix yields a 4X4 matrix
#    [,1] [,2] [,3] [,4]
#[1,]  1    2    3    4
#[2,] -1   -2   -3   -4
#[3,]  1    2    3    4
#[4,] -1   -2   -3   -4

mx=matrix(x,2)
#Convert a vector y into a matrix of 2 rows. 
my=matrix(y,2)
my
#The matrix elements go by column, first column, second, etc
#    [,1] [,2]
#[1,]  1    3
#[2,]  2    4

dim(my) 
#find dimensions of a matrix
#[1] 2 2

as.vector(my) 
#Convert a matrix to a vector, also via columns 
#[1] 1 2 3 4

mx*my 
#multiplication between each pair of elements
#    [,1] [,2]
#[1,]  1    3
#[2,] -2   -4

mx/my  
#division between each pair of elements
#    [,1] [,2]
#[1,]  1.0  0.3333333
#[2,] -0.5 -0.2500000

mx-2*my
#    [,1] [,2]
#[1,] -1   -5
#[2,] -5   -9

mx%*%my 
#matrix multiplication 
#    [,1] [,2]
#[1,]  3    7
#[2,] -3   -7

det(my) 
#determinant of a square matrix
#[1] -2

myinv = solve(my) 
# find inverse of a matrix 
myinv
#    [,1] [,2]
#[1,] -2    1.5
#[2,]  1   -0.5

myinv%*%my 
#verifies the inverse of a matrix 
#    [,1] [,2]
#[1,]  1    0
#[2,]  0    1

diag(my) 
#output the diagonal vector of a matrix
#[1] 1 4

myeig=eigen(my)
#yields eigenvalues and unit eigenvectors
myeig
#$values 
#Gives the two eigenvalues
#[1] 5.3722813 -0.3722813

#$vectors 
#Gives the two eigenvectors
#    [,1]        [,2]
#[1,] -0.5657675 -0.9093767
#[2,] -0.8245648  0.4159736

myeig$values 
#output only eigenvalues 
myeig$vectors
#output only eigenvectors

mysvd = svd(my) 
#SVD decomposition of a matrix M=UDV’ 
#SVD can be done for any m-by-n rectangular matrix 
mysvd 
#output d, U, and V

#$d #SVD eigenvalues
#[1] 5.4649857 0.3659662

#$u #spatial eigenvectors
#     [,1]       [,2]
#[1,] -0.5760484 -0.8174156
#[2,] -0.8174156  0.5760484

#$v #temporal eigenvectors
#     [,1]       [,2]
#[1,] -0.4045536  0.9145143
#[2,] -0.9145143 -0.4045536

mysvd$d 
#output d only, as a vector 
U=mysvd$u 
#Output the U matrix 
D=diag(mysvd$d) 
#Generate the D matrix

V=mysvd$v 
#Output the V matrix
U%*%D%*%t(V) 
#Recover the original matrix 
my 
#    [,1] [,2]
#[1,]  1    3
#[2,]  2    4

ysol=solve(my,c(1,3)) 
#solve linear equations matrix %*% x = b 
ysol 
#the resulting solution of solve(matrix, b)
#[1] 2.5 -0.5

my%*%ysol 
#verifies the solution
#   [,1] 
#[1,] 1 
#[2,] 3


#Statistics
###########

x=rnorm(10) 
#generate 10 normally distributed numbers 
x
#[1] -0.3091103 -0.2955515 -0.1336243 -0.0199047 -1.0609169  0.7070698
#[7]  0.5847710  0.8837731 -0.5215831 -0.9766754

mean(x)
#[1] -0.1141752

var(x)
#[1] 0.4494711

sd(x)
#[1] 0.670426

median(x)
#[1] -0.2145879

quantile(x)
#      0%        25%        50%        75%       100% 
#-1.0609169 -0.4684649 -0.2145879  0.4336021  0.8837731 

range(x) 
#yields the min and max of x
#[1] -1.0609169  0.8837731

max(x)
#[1] 0.8837731

boxplot(x) 
#yields the box plot of x

w=rnorm(1000) 
#generate 1000 normally distributed random numbers N(0,1) 
z=rnorm(10000, mean=10, sd=5) 
#generate 100 random numbers following N(10,5ˆ2)
#mean = 10, standard deviation =5
summary(rnorm(12)) 
#statistical summary of the data sequence
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#-1.5927 -0.2750  0.3146  0.1114  0.6498  1.4910 

hist(w) 
#plot the histogram of 1000 random numbers


#R Tutorials
############

#Commands to input data files

# mydata <- read.csv("mydata.csv") 
# read csv file named "mydata.csv"

#mydata <- read.table("mydata.txt") 
# read text file named "my data.txt"

#library(gdata) 
# load the gdata package 

#mydata = read.xls("mydata.xls") 
# read an excel file

#library(foreign) 
# load the foreign package 

#mydata = read.mtp("mydata.mtp") 
# read from .mtp file

#library(foreign) 
# load the foreign package 

#mydata = read.spss("myfile", to.data.frame=TRUE)
#read a spss file

#ff <- tempfile()
#cat(file = ff, "123456", "987654", sep = "\n") 
#read.fortran(ff, c("F2.1","F2.0","I2"))
#read a fotran file

# library(ncdf4)
# load the ncdf4 package 

#ncin <- ncdf4::nc_open("ncfname") 
# open a NetCDF file

#lon <- ncvar_get(ncin, "lon") 
#read data "lon" from a netCDF file into R

#library("rjson")
# load the rjson package 

#jd<- fromJSON(file = "dat.json") 
# read data from a JSON file dat.json


#library(ncdf4) 
#Suppose the following error message pops up
#When you load ncdf4 package
#Error in library(ncdf4) : there is no package called ncdf4 

#You can install the R package by
#install.packages("ncdf4")

#R packages: animation, chron, e1071, fields, ggplot2, lattice,
#latticeExtra, maps, mapdata, mapproj, matrixStats, ncdf4,
#NLRoot, RColorBrewer, rgdal, rasterVis, raster, rjson, sp, TTR

#The zipped data for this book can be downloaded from: 
#climatemathematics.sdsu.edu/data.zip

#To load a single package, such as "animation", you can do
library(animation)

#You can also load all these packages in one shot using
# pacman
install.packages("pacman")
library(pacman)
pacman::p_load(animation, chron, e1071, fields, ggplot2, lattice,
               latticeExtra, maps, mapdata, mapproj, matrixStats, ncdf4,
               NLRoot, RColorBrewer, rgdal, rasterVis, raster, rjson, sp, TTR)
